Fix when in the voting phase, there were more voting stages than players count
Plugily-Projects/BuildBattle pull request #67
Opened 2022-10-13 15:03 UTC by montlikadani

2022-10-13 17:18 UTC, Tigerpanzer02 requested changes
Would cause to get one higher the possible ones

2022-10-13 17:53 UTC, montlikadani commented on src/main/java/plugily/projects/buildbattle/arena/ArenaManager.java
> +    Plot partyPlot = plots.get(plots.size() == 1 ? 0 : plugin.getRandom().nextInt(plots.size()));
I mean, if plots list size is 1 randomizing between 0..0 bound, you see, is unnecessary.

2022-10-13 18:07 UTC, Tigerpanzer02 commented on src/main/java/plugily/projects/buildbattle/arena/ArenaManager.java
> +    Plot partyPlot = plots.get(plots.size() == 1 ? 0 : plugin.getRandom().nextInt(plots.size()));
size 6 get 6 would cause out of bounds

2022-10-13 18:19 UTC, montlikadani commented on src/main/java/plugily/projects/buildbattle/arena/ArenaManager.java
> +    Plot partyPlot = plots.get(plots.size() == 1 ? 0 : plugin.getRandom().nextInt(plots.size()));
`Random#nextInt` will not returns the value gave in the parameter. `nextInt` start from 0..5, that is why it is mentioned in the nextInt doc "between the specified bound"

2022-10-14 04:37 UTC, Tigerpanzer02 commented on src/main/java/plugily/projects/buildbattle/arena/ArenaManager.java
> +    Plot partyPlot = plots.get(plots.size() == 1 ? 0 : plugin.getRandom().nextInt(plots.size()));
True my fault from other project

2022-10-14 04:37 UTC, merged